title: Harttle Land
description: 致力于简单的、一致的、高效的前端开发
url: http://harttle.com
author: Harttle
twitter:
  username: harttleharttle
logo: assets/img/favicon.png
keywords: 
  - Web
  - HTML
  - CSS
  - JavaScript
  - C++
  - Linux
  - Bash
  - Vim

permalink: /:year/:month/:day/:title.html
paginate: 7
paginate_path: "page:num"

markdown: kramdown
markdown_ext:  md
excerpt_separator: "<!--more-->"
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
lsi: false

exclude: ['README.md', '.*', 'scripts/', 'bak', 'Gemfile']

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

