name: Harttle Land
url: http://harttle.github.io

permalink: none

paginate: 5
paginate_path: "/page:num"

highlighter: pygments

markdown: redcarpet
markdown_ext:  md
redcarpet:
    extensions: [no_intra_emphasis,tables,autolink,disable_indented_code_blocks,fenced_code_blocks]

exclude: ['README.md', '.*']


gems:
  - jekyll-sitemap
