name: Harttle Land
url: http://harttle.github.io

permalink: none

paginate: 4
paginate_path: "page:num"

highlighter: pygments

markdown: redcarpet
markdown_ext:  md
redcarpet:
    extensions: [no_intra_emphasis,tables,autolink,disable_indented_code_blocks,fenced_code_blocks]

exclude: ['README.md', '*.sh', '.*']

gems:
  - jekyll-sitemap

cate_icons:
  reading: "fa-book"
  development: "fa-code"
  linux: "fa-linux"
  misc: "fa-file-text"
